apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: video-process
  name: video-process
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: video-process
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: video-process
    spec:
      containers:
        - args:
            - python
            - video_analytics/udf_process.py
          env:
            - name: DISPLAY
              value: :0
          image: jirnsr/python_ia:1.2
          name: video-process
          resources: {}
          volumeMounts:
            - mountPath: /tmp/.X11-unix
              name: video-process-claim0
      restartPolicy: Always
      volumes:
        - name: video-process-claim0
          persistentVolumeClaim:
            claimName: video-process-claim0
status: {}
